/**
 * Plays spoken instructions.
 *
 * Primary path: a real audio clip generated by the backend `/tts` endpoint and
 * played through an <audio> element. This works in every browser and inside
 * embedded/preview iframes because it does not depend on locally installed
 * speech-synthesis voices.
 *
 * Fallback path: the Web Speech API (speechSynthesis), used only if the audio
 * clip fails to load/play.
 */
export class AudioInstructor {
  private static instance: AudioInstructor;
  private currentLanguage = 'en';
  private queue: string[] = [];
  private lastSpoken: string[] = [];
  /** Bumped on every new speak()/stop() so stale callbacks are ignored. */
  private token = 0;
  private current: HTMLAudioElement | null = null;

  private constructor() {}

  public static getInstance(): AudioInstructor {
    if (!AudioInstructor.instance) {
      AudioInstructor.instance = new AudioInstructor();
    }
    return AudioInstructor.instance;
  }

  /** Accepts an audio language code ("en") or a BCP-47 tag ("en-US"). */
  public setLanguage(lang: string) {
    this.currentLanguage = lang;
  }

  public isAvailable() {
    return Boolean(this.getAudioCtor() || this.getSynth());
  }

  /** Speak a single instruction immediately, replacing anything in progress. */
  public play(text: string) {
    return this.speak([text]);
  }

  /** Queue an ordered sequence of phrases (e.g. word, sentence, word). */
  public enqueue(texts: string[]) {
    return this.speak(texts.filter(Boolean));
  }

  /** Replay the most recent instruction (or sequence). */
  public replay() {
    if (this.lastSpoken.length === 0) return false;
    return this.speak([...this.lastSpoken]);
  }

  public pause() {
    this.current?.pause();
    this.getSynth()?.pause();
  }

  public resume() {
    void this.current?.play?.()?.catch?.(() => {});
    this.getSynth()?.resume();
  }

  public stop() {
    this.token += 1;
    this.queue = [];
    this.stopCurrentClip();
    this.getSynth()?.cancel();
  }

  private speak(texts: string[]) {
    if (typeof window === 'undefined' || texts.length === 0) return false;
    if (!this.getAudioCtor() && !this.getSynth()) return false;

    this.token += 1;
    const token = this.token;
    this.queue = [...texts];
    this.lastSpoken = [...texts];
    this.stopCurrentClip();
    this.getSynth()?.cancel();
    this.drain(token);
    return true;
  }

  private drain(token: number) {
    if (token !== this.token) return;
    const next = this.queue.shift();
    if (next === undefined) return;
    this.playPhrase(next, token);
  }

  private advance(token: number) {
    if (token === this.token) this.drain(token);
  }

  private playPhrase(text: string, token: number) {
    const AudioCtor = this.getAudioCtor();
    if (!AudioCtor) {
      this.speakViaSynth(text, token);
      return;
    }

    let settled = false;
    const onFail = () => {
      if (settled) return;
      settled = true;
      this.speakViaSynth(text, token); // try speech synthesis for this phrase
    };
    const onDone = () => {
      if (settled) return;
      settled = true;
      this.advance(token);
    };

    let audio: HTMLAudioElement;
    try {
      audio = new AudioCtor(this.ttsUrl(text));
    } catch {
      onFail();
      return;
    }
    this.current = audio;
    audio.onended = onDone;
    audio.onerror = onFail;
    const played = audio.play?.();
    if (played && typeof played.catch === 'function') played.catch(onFail);
  }

  private speakViaSynth(text: string, token: number) {
    if (token !== this.token) return;
    const synth = this.getSynth();
    const Utterance = this.getUtteranceConstructor();
    if (!synth || !Utterance) {
      this.advance(token); // no fallback available: skip to the next phrase
      return;
    }

    let settled = false;
    const done = () => {
      if (settled) return;
      settled = true;
      this.advance(token);
    };

    const utterance = new Utterance(text);
    utterance.lang = this.synthLang();
    utterance.rate = 0.9;
    utterance.pitch = 1;
    utterance.volume = 1;
    utterance.onend = done;
    utterance.onerror = done;
    try {
      synth.cancel();
      synth.speak(utterance);
    } catch {
      done();
    }
  }

  private ttsUrl(text: string) {
    const lang = this.currentLanguage.split('-')[0];
    return `/tts?lang=${encodeURIComponent(lang)}&text=${encodeURIComponent(text)}`;
  }

  private synthLang() {
    return this.currentLanguage.includes('-') ? this.currentLanguage : `${this.currentLanguage}-US`;
  }

  private stopCurrentClip() {
    if (!this.current) return;
    try {
      this.current.pause();
    } catch {
      /* ignore */
    }
    this.current.onended = null;
    this.current.onerror = null;
    this.current = null;
  }

  private getAudioCtor() {
    return typeof window !== 'undefined' && 'Audio' in window ? window.Audio : null;
  }

  private getSynth() {
    return typeof window !== 'undefined' && 'speechSynthesis' in window ? window.speechSynthesis : null;
  }

  private getUtteranceConstructor() {
    return typeof window !== 'undefined' && 'SpeechSynthesisUtterance' in window ? window.SpeechSynthesisUtterance : null;
  }
}
